import Head from "next/head";
import { useState } from "react";

import Projects from "./components/Projects";
import Contact from "./components/contact";
import About from "./components/About";
import Blockquote from "./components/Blockquote";
import Navbar from "./components/Navbar";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  var scaleEffect = "hover:scale-x-105 transition-all ease-in-out";
  return (
    <>
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="font-mono px-1 sm:px-10 overflow-hidden dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
         <Navbar darkMode={darkMode} setDarkMode={setDarkMode}/>
         <Blockquote/>
        </section>
        {/* Quote section  */}

        <section>
          <div
            className={
              darkMode
                ? "rounded-2xl shadow-md"
                : "rounded-2xl bg-white shadow-lg"
            }
          >
            {/* <div className="text-center text-gray-800 p-7">
              <p className="text-md text-gray-800 dark:text-gray-200">
                Spiders are the only web developers who love finding bugs.
              </p>
              <p className="text-md text-right mr-20 text-gray-800 dark:text-gray-200">
                -Anonymous
              </p>
            </div> */}
          </div>
        </section>

        <section className="py-10">
          <About />
        </section>

        <Projects scaleEffect={scaleEffect} />
    
      </main>
    </div>
      {/* <section className="m-0 p-0 rounded-xl overflow-hidden w-full shadow-2xl">
        <Contact />
      </section> */}
    
    </>
  );
}
